name: Build and publish pine-roots

# on:
#   release:
#     types: [created]
on: push

jobs:
  build-and-publish-pine-roots:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: roots

    steps:
      - name: âœ… Checkout
        uses: actions/checkout@v2
      - name: ğŸ  Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
          # registry-url: https://npm.pkg.github.com/
      - name: âš™ï¸ Install dependencies
        run: npm ci
      - name: ğŸ‘·ğŸ½â€â™‚ï¸ Build package
        run: npm run build
      - name: ğŸš€ Publish to npm
        id: publish
        # run: npm publish
        # env:
        #   NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          registry: https://npm.pkg.github.com/
          dry-run: true
      - if: steps.publish.outputs.type != 'none'
        run: |
          echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"