name: Build and publish pine-roots

# on:
#   release:
#     types: [created]
on: push


jobs:
  build-and-publish-pine-roots:
    runs-on: ubuntu-latest

    steps:
      - name: âœ… Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: ğŸ  Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - name: âš™ï¸ Install dependencies
        run: npm ci
      - name: ğŸ‘·ğŸ½â€â™‚ï¸ Build package
        run: npm run build
      - name: ğŸš€ Publish to npm
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"

          lerna version --conventional-commits --conventional-graduate --yes
          lerna publish from-git --yes
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}